chore(scripts): cleanup and add justfile

diff --git a/scripts/bump b/scripts/bump
--- a/scripts/bump
+++ b/scripts/bump
@@ -1,8 +1,42 @@
 #!/bin/sh
-trap 'rm -f "$CARGO_TMP_PATH" "$CARGO_BAK_PATH"' EXIT
+cleanup() {
+
+    # only on failure
+    if [ $? -ne 0 ]; then
+        [ -f "$CARGO_BAK_PATH" ] && mv "$CARGO_BAK_PATH" "$CARGO_PATH"
+    else
+        rm -f "$CARGO_BAK_PATH" || true
+    fi
+
+    rm -f "$CARGO_TMP_PATH" || true
+    rm -f "$CMD_LOG_PATH" || true
+}
+
+trap cleanup EXIT
 
 perror() {
-    printf "ERROR: %s\n" "$*" >&2
+    printf "ERROR: $1\n" "${@:2}" >&2
+}
+
+pusage() {
+    printf "%s\n" "$USAGE"
+}
+
+run() {
+    echo "$*"
+    "$@" >&2
+}
+
+try() {
+    if ! run "$@" 2>"$CMD_LOG_PATH"; then
+        perror "$*"
+        cat "$CMD_LOG_PATH" >&2
+        exit 1
+    fi
+}
+
+log() {
+    cat "$CMD_LOG_PATH"
 }
 
 if ! REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null); then
@@ -15,11 +49,13 @@ CARGO_LOCK_PATH="$REPO_ROOT/Cargo.lock"
 CARGO_PATH="$REPO_ROOT/Cargo.toml"
 CARGO_TMP_PATH="$CARGO_PATH.bump.tmp"
 CARGO_BAK_PATH="$CARGO_PATH.bak"
+CMD_LOG_PATH="$REPO_ROOT/bump_cmd.log"
+
 
 USAGE="Usage: bump [major|minor|patch] <message>"
 
 if [ -z "$1" ] || [ -z "$2" ]; then
-    perror "missing argument\n%s" "$USAGE"
+    perror "missing argument" && pusage
     exit 1
 fi
 
@@ -32,7 +68,7 @@ case "$BUMP" in
     minor) ;;
     patch) ;;
     *) 
-        perror "invalid target %s\n%s" "$BUMP" "$USAGE"
+        perror "invalid target %s" "$BUMP" && pusage
         exit 1
         ;;
 esac
@@ -89,22 +125,17 @@ NEW="version = \"$BUMPED\""
 sed "/\[package\]/,/^\[.*/s/^$OLD/$NEW/" "$CARGO_PATH" > "$CARGO_TMP_PATH"
 
 
+# update Cargo.toml
 mv "$CARGO_PATH" "$CARGO_BAK_PATH"
 mv "$CARGO_TMP_PATH" "$CARGO_PATH"
 
-set -ex
-if ! cargo update > /dev/null 2>&1; then
-    perror "cargo update failed"
-    mv "$CARGO_BAK_PATH" "$CARGO_PATH"
-    exit 1
-fi
-{ set +ex; } 2>/dev/null
 
-set -ex
-git add "$CARGO_PATH" "$CARGO_LOCK_PATH" > /dev/null 2>&1
+try cargo update
 
-git commit -m "chore: bump to v$BUMPED" > /dev/null 2>&1
+try git add "$CARGO_PATH" "$CARGO_LOCK_PATH" 
 
-git tag "v$BUMPED" -m "$MESSAGE" > /dev/null 2>&1
-{ set +ex; } 2>/dev/null
+try git commit -m "chore: bump to v$BUMPED" 
+
+try git tag "v$BUMPED" -m "$MESSAGE" 
+
 
